server.port=8080

spring.datasource.url=jdbc:postgresql:///sopradb?cloudSqlInstance=sopra-fs26-group-31-server:europe-west6:sopra-fs26-group-31-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true